// This file is auto-generated by @hey-api/openapi-ts

export const errorSchema = {
  type: 'object',
  properties: {
    status: {
      const: 'error',
      type: 'string'
    },
    message: {
      type: 'string'
    },
    errorCode: {
      anyOf: [
        {
          const: 'user_exists',
          type: 'string'
        },
        {
          const: 'not_found',
          type: 'string'
        },
        {
          const: 'invalid_email_password',
          type: 'string'
        },
        {
          const: 'email_not_verified',
          type: 'string'
        },
        {
          const: 'invalid_token',
          type: 'string'
        },
        {
          const: 'unauthorized',
          type: 'string'
        },
        {
          const: 'too_many_requests',
          type: 'string'
        },
        {
          const: 'internal_server_error',
          type: 'string'
        },
        {
          const: 'route_not_found',
          type: 'string'
        },
        {
          const: 'validation_error',
          type: 'string'
        },
        {
          const: 'email_already_verified',
          type: 'string'
        }
      ]
    },
    errors: {
      type: 'array',
      items: {}
    }
  },
  required: ['status', 'message', 'errorCode']
} as const
