// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch'
import type {
  GetApiV1HealthcheckError,
  GetApiV1HealthcheckResponse,
  GetApiV1TokenStatsData,
  GetApiV1TokenStatsError,
  GetApiV1TokenStatsResponse,
  PostApiV1TokenStatsData,
  PostApiV1TokenStatsError,
  PostApiV1TokenStatsResponse,
  GetApiV1TokenStatsLatestData,
  GetApiV1TokenStatsLatestError,
  GetApiV1TokenStatsLatestResponse
} from './types.gen'

export const client = createClient(createConfig())

export const getApiV1Healthcheck = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetApiV1HealthcheckResponse,
    GetApiV1HealthcheckError,
    ThrowOnError
  >({
    ...options,
    url: '/api/v1/healthcheck'
  })
}

export const getApiV1TokenStats = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1TokenStatsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetApiV1TokenStatsResponse,
    GetApiV1TokenStatsError,
    ThrowOnError
  >({
    ...options,
    url: '/api/v1/token-stats/'
  })
}

export const postApiV1TokenStats = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1TokenStatsData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    PostApiV1TokenStatsResponse,
    PostApiV1TokenStatsError,
    ThrowOnError
  >({
    ...options,
    url: '/api/v1/token-stats/'
  })
}

export const getApiV1TokenStatsLatest = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1TokenStatsLatestData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetApiV1TokenStatsLatestResponse,
    GetApiV1TokenStatsLatestError,
    ThrowOnError
  >({
    ...options,
    url: '/api/v1/token-stats/latest'
  })
}
