// This file is auto-generated by @hey-api/openapi-ts

export type error = {
  status: 'error'
  message: string
  errorCode:
    | 'user_exists'
    | 'not_found'
    | 'invalid_email_password'
    | 'email_not_verified'
    | 'invalid_token'
    | 'unauthorized'
    | 'too_many_requests'
    | 'internal_server_error'
    | 'route_not_found'
    | 'validation_error'
    | 'email_already_verified'
  errors?: Array<unknown>
}

export type GetApiV1HealthcheckResponse = {
  status: string
}

export type GetApiV1HealthcheckError = unknown

export type GetApiV1TokenStatsData = {
  query: {
    aggregate?: 'sum' | 'avg' | 'max'
    breakdown?: 'day' | 'week' | 'month' | 'year'
    endDate?: Date
    key: string
    startDate?: Date
    type: 'token_holder_count' | 'token_price' | 'nft_total_supply'
  }
}

export type GetApiV1TokenStatsResponse = {
  status: 'success'
  data: Array<{
    value: string
    date: Date
    key: string
    type: 'token_holder_count' | 'token_price' | 'nft_total_supply'
  }>
}

export type GetApiV1TokenStatsError = error

export type PostApiV1TokenStatsData = {
  body: {
    type: 'token_holder_count' | 'token_price' | 'nft_total_supply'
    key: string
  }
}

export type PostApiV1TokenStatsResponse = {
  status: 'success'
  data: null
}

export type PostApiV1TokenStatsError = error

export type GetApiV1TokenStatsLatestData = {
  query: {
    key: string
    type: 'token_holder_count' | 'token_price' | 'nft_total_supply'
  }
}

export type GetApiV1TokenStatsLatestResponse = {
  status: 'success'
  data: {
    value: string
    date: Date
    key: string
    type: 'token_holder_count' | 'token_price' | 'nft_total_supply'
  }
}

export type GetApiV1TokenStatsLatestError = error
